#:schema node_modules/wrangler/config-schema.json
name = "exodus-ing"
compatibility_date = "2024-07-01"
pages_build_output_dir = ".svelte-kit/cloudflare"

######## LOCAL environment config ########

[[d1_databases]]
binding = "EXODUSING_DB"
database_name = "exodus-ing"
database_id = "fafc0684-b91c-4195-8e70-e317f0ed2441"

######## PREVIEW environment config ########

[env.preview.vars]
EXODUSING_HOST = "https://preview.exodus.ing"
NODE_VERSION = "22.14.0"

[[env.preview.d1_databases]]
binding = "EXODUSING_DB"
database_name = "exodus-ing"
database_id = "fafc0684-b91c-4195-8e70-e317f0ed2441"

######## PRODUCTION environment config ########

[env.production.vars]
EXODUSING_HOST = "https://exodus.ing"
NODE_VERSION = "22.14.0"

[[env.production.d1_databases]]
binding = "EXODUSING_DB"
database_name = "exodus-ing"
database_id = "fafc0684-b91c-4195-8e70-e317f0ed2441"
